spring:
  application:
    name: chatbot-api
  datasource:
    url: ${JDBC_POSTGRES}
    username: neondb_owner
    password: ${NEON_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  ai:
    openai:
      api-key: ${GEMINI_API_KEY}
      base-url: "https://generativelanguage.googleapis.com/v1beta/openai"
      chat:
        options:
          model: "gemini-1.5-flash"
          temperature: 0.7
whatsapp:
  api:
    verify-token: ${WHATSAPP_VERIFY_TOKEN}
tesseract:
  datapath: C:/tessdata
  language: por
telegram:
  bot:
    username: rival_atendimento_bot
    token: ${TELEGRAM_BOT_TOKEN}